### ISSUE TITLE
Differences between libperseus-sdr and perseususb.dll

### ISSUE THREAD

**Issue by EdFuentetaja** [Microtelecom/libperseus-sdr#4]
This is more a question than an issue, I'm curious why there are two different APIs for Perseus. One is this one, defined in perseus-sdr.h, the other is in the "MicrotelecomSDRDKv33," implemented in perseususb.dll. Since it seems that both are coming from Mr. Nico Palermo, I wonder why there are two similar implementations. Is it that one is a wrapper of the other? Which one should be preferred? Which has a bigger chance of being continued?

To fully disclose my interest on Perseus, I'm involved in a project that uses Perseus. We extract the IQ from Perseus and process it in some other applications. The fact that perseususb.dll is only available on windows 32 bits is limiting. I'm very interested in our project running also on Linux and Windows 64. Definitely libperseus-sdr seems very promising.

I want to thank Mr. Andrea for sharing this software and for his dedication and support. Any improvements that we might be able to come up with, I'll be more than happy to share with him and the community.

Thanks again for the excellent job,

Eduardo

**Comment by amontefusco** [comment]
> I'm curious why there are two 
> different APIs for Perseus. One is this one, defined in perseus-sdr.h, 
> the other is in the "MicrotelecomSDRDKv33," 
> implemented in perseususb.dll. 
> Since it seems that both are coming from Mr. Nico Palermo, 

You are right, Mr. Nico Palermo wrote both libs, just at different time.
Consider that, at its inception,  the libperseus-sdr was meant to be
a *nix library only.

> I wonder why there are two similar implementations.

Because, in the origin, each one was specific to a different
platform.
Only recently (2014), Nico suggested me to do a porting of libperseus-sdr
on Windows, and so libperseus-sdr became a sort of universal tools.

> Is it that one is a wrapper of the other? 

As far as I know, the code base of two libraries is totally unrelated one to each other.

> Which one should be preferred ?

IMO, it depends on whether  is your application meant to be multi platform or not: in case it is, select libperseus-sdr, otherwise stay with the SDRDK.

Please remember that above are my personal opinions, not the Microtelecom official position.
